# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    # Set TRUSTED_PROXIES to an empty value to stop trusting forwarded headers altogether.
    trusted_proxies: '%env(string:TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port' ]
    assets:
        version_strategy: 'App\Infrastructure\Http\AssetVersioningStrategy'

when@dev:
    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
