name: 'coverage-report'
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup CI environment
        uses: ./.github/actions/setup-env

      - name: Run test suite
        run: vendor/bin/paratest --order-by=random --fail-on-incomplete --log-junit junit.xml --coverage-clover=clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clover.xml
          fail_ci_if_error: false
